[project]
name = "dagster_etl_project"
requires-python = ">=3.9,<3.14"
version = "0.1.0"
dependencies = [
    "dagster==1.11.5",
    "dagster-dbt>=0.27.5",
    "dagster-aws>=0.23",
    "dagster-dbt>=0.23",
    "dbt-duckdb>=1.8",
    "duckdb>=1.0",
    "dlt[duckdb]>=1.5",
    "pandas>=2.0",
    "scikit-learn>=1.3",
    "python-dotenv>=1.0",
    "polars",
    "dagster-duckdb>=0.27.5",
    "pyarrow>=21.0.0",
    "dagster-duckdb-polars>=0.27.5",
]


[dependency-groups]
dev = [
    "dagster-webserver",
    "dagster-dg-cli",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "dagster_etl_project"
registry_modules = [
    "dagster_etl_project.components.*",
]


